name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set MLflow tracking URI
        run: |
          unset MLFLOW_TRACKING_URI
          rm -f ~/.mlflow/mlflow.yml || true


      - name: Train model
        run: |
          rm -rf ~/.mlflow
          export MLFLOW_TRACKING_URI=mlruns
          python app/train.py

      - name: Run tests
        run: pytest

      - name: Train model
        run: |
          python app/train.py

      - name: Run tests
        run: |
          pytest
